# Describes the role that gives the
# federated Prometheus access to specific
# resources inside the openshift-monitoring
# namespace for service discovery purposes.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-christian
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch