# Descibes the federation scraping config and the security
# config to get passed the OpenShift OAuth proxy (see 
# tlsConfig section + bearerTokenFile).
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: christian
  name: federate
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    params:
      match[]: # federate config / what metrics i want
      - '{job="prometheus"}'
      - '{__name__=~"job:.*"}'
    path: /federate # endpoint to scrape
    port: web
    scheme: https # important
    tlsConfig: # important
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: prometheus-k8s.openshift-monitoring.svc
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token #important
  jobLabel: app
  namespaceSelector:
    matchNames:
    - openshift-monitoring # where the Cluster Monitoring Prometheus is running
  selector:
    matchLabels:
      prometheus: k8s